services:
  - type: web
    name: telegram-affiliate-bot
    env: python
    plan: free
    buildCommand: |
      echo "python-3.11.9" > runtime.txt
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
